apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: bitops-system-admin
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 'v5.46.6'
    helm:
      parameters:
        - name: create_namespace
          value: 'true'
  destination:
    namespace: bitops-system
    name: dev-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
