apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: bitops-system-admin
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: digital
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: '0.8.3'
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    namespace: digital
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
