apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: bitops-system-admin
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: digital
    name: in-cluster
  project: digital
  source:
    path: general/helm-guestbook
    repoURL: https://github.com/morey-tech/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
