apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: bitops-system-admin
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bitops-system
    name: dev-cluster
  project: default
  source:
    path: general/helm-guestbook
    repoURL: https://github.com/morey-tech/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

    
